drop table if exists group_messages cascade;
drop table if exists group_members cascade;
drop table if exists groups cascade;
drop table if exists private_chats cascade;
drop table if exists stories cascade;
drop table if exists typing_status cascade;
drop table if exists users cascade;

create table users (
  id bigint generated by default as identity primary key,
  uid text unique,
  username text unique,
  email text,
  avatar text,
  bio text,
  online boolean default false,
  last_seen timestamp,
  created_at timestamp default now()
);

create table private_chats (
  id bigint generated by default as identity primary key,
  sender_id text,
  receiver_id text,
  text text,
  image text,
  audio text,
  type text,
  seen boolean default false,
  created_at timestamp default now()
);

create table stories (
  id bigint generated by default as identity primary key,
  uid text,
  image text,
  text text,
  created_at timestamp default now(),
  expires_at timestamp
);

create table typing_status (
  id bigint generated by default as identity primary key,
  sender_id text,
  receiver_id text,
  typing boolean default false
);

create table groups (
  id bigint generated by default as identity primary key,
  name text,
  image text,
  created_by text,
  created_at timestamp default now()
);

create table group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  uid text,
  role text default 'member'
);

create table group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  sender_id text,
  text text,
  image text,
  audio text,
  type text,
  created_at timestamp default now()
);