drop table if exists message_reactions cascade;
drop table if exists deleted_messages cascade;
drop table if exists group_messages cascade;
drop table if exists group_members cascade;
drop table if exists groups cascade;
drop table if exists private_chats cascade;
drop table if exists stories cascade;
drop table if exists typing_status cascade;
drop table if exists users cascade;

create table users (
  id bigint generated by default as identity primary key,
  uid text unique not null,
  username text unique not null,
  email text,
  avatar text,
  bio text default '',
  online boolean default false,
  last_seen timestamp default now(),
  notifications boolean default true,
  dark_mode boolean default true,
  created_at timestamp default now()
);

create table private_chats (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  receiver_id text not null,
  text text,
  image text,
  audio text,
  type text default 'text',
  edited boolean default false,
  deleted_for_everyone boolean default false,
  seen boolean default false,
  created_at timestamp default now()
);

create table deleted_messages (
  id bigint generated by default as identity primary key,
  message_id bigint,
  uid text,
  chat_type text default 'dm'
);

create table message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint,
  uid text,
  emoji text,
  chat_type text default 'dm',
  created_at timestamp default now()
);

create table typing_status (
  id bigint generated by default as identity primary key,
  sender_id text,
  receiver_id text,
  typing boolean default false,
  updated_at timestamp default now()
);

create table stories (
  id bigint generated by default as identity primary key,
  uid text,
  image text,
  text text,
  bg text default '#00a884',
  created_at timestamp default now(),
  expires_at timestamp
);

create table groups (
  id bigint generated by default as identity primary key,
  name text,
  image text,
  created_by text,
  created_at timestamp default now()
);

create table group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  uid text,
  role text default 'member'
);

create table group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  sender_id text,
  text text,
  image text,
  audio text,
  type text default 'text',
  edited boolean default false,
  deleted_for_everyone boolean default false,
  created_at timestamp default now()
);

alter table users enable row level security;
alter table private_chats enable row level security;
alter table deleted_messages enable row level security;
alter table message_reactions enable row level security;
alter table typing_status enable row level security;
alter table stories enable row level security;
alter table groups enable row level security;
alter table group_members enable row level security;
alter table group_messages enable row level security;

create policy "users all" on users for all to authenticated using (true) with check (true);
create policy "private chats all" on private_chats for all to authenticated using (true) with check (true);
create policy "deleted messages all" on deleted_messages for all to authenticated using (true) with check (true);
create policy "reactions all" on message_reactions for all to authenticated using (true) with check (true);
create policy "typing all" on typing_status for all to authenticated using (true) with check (true);
create policy "stories all" on stories for all to authenticated using (true) with check (true);
create policy "groups all" on groups for all to authenticated using (true) with check (true);
create policy "group members all" on group_members for all to authenticated using (true) with check (true);
create policy "group messages all" on group_messages for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;

drop policy if exists "Allow uploads insert" on storage.objects;
drop policy if exists "Allow uploads select" on storage.objects;
drop policy if exists "Allow uploads update" on storage.objects;
drop policy if exists "Allow uploads delete" on storage.objects;

create policy "Allow uploads insert"
on storage.objects for insert to authenticated
with check (bucket_id = 'uploads');

create policy "Allow uploads select"
on storage.objects for select to public
using (bucket_id = 'uploads');

create policy "Allow uploads update"
on storage.objects for update to authenticated
using (bucket_id = 'uploads')
with check (bucket_id = 'uploads');

create policy "Allow uploads delete"
on storage.objects for delete to authenticated
using (bucket_id = 'uploads');