-- iChat V6 safe migration
-- Run this in Supabase SQL editor. It does not drop existing app tables.

create table if not exists users (
  id bigint generated by default as identity primary key,
  uid text unique not null,
  username text unique not null,
  email text,
  avatar text,
  bio text default '',
  online boolean default false,
  last_seen timestamp default now(),
  notifications boolean default true,
  dark_mode boolean default true,
  created_at timestamp default now()
);

alter table users add column if not exists avatar text;
alter table users add column if not exists bio text default '';
alter table users add column if not exists online boolean default false;
alter table users add column if not exists last_seen timestamp default now();
alter table users add column if not exists notifications boolean default true;
alter table users add column if not exists dark_mode boolean default true;
alter table users add column if not exists hide_online boolean default false;
alter table users add column if not exists hide_last_seen boolean default false;

create table if not exists private_chats (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  receiver_id text not null,
  text text,
  image text,
  audio text,
  type text default 'text',
  reply_to bigint,
  edited boolean default false,
  deleted_for_everyone boolean default false,
  seen boolean default false,
  created_at timestamp default now()
);

alter table private_chats add column if not exists image text;
alter table private_chats add column if not exists audio text;
alter table private_chats add column if not exists type text default 'text';
alter table private_chats add column if not exists reply_to bigint;
alter table private_chats add column if not exists edited boolean default false;
alter table private_chats add column if not exists deleted_for_everyone boolean default false;
alter table private_chats add column if not exists seen boolean default false;
alter table private_chats add column if not exists file_url text;
alter table private_chats add column if not exists file_name text;
alter table private_chats add column if not exists file_type text;

create table if not exists deleted_messages (
  id bigint generated by default as identity primary key,
  message_id bigint,
  uid text,
  chat_type text default 'dm'
);

create table if not exists message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint,
  uid text,
  emoji text,
  chat_type text default 'dm',
  created_at timestamp default now()
);

create table if not exists typing_status (
  id bigint generated by default as identity primary key,
  sender_id text,
  receiver_id text,
  typing boolean default false,
  updated_at timestamp default now(),
  unique(sender_id, receiver_id)
);

create table if not exists stories (
  id bigint generated by default as identity primary key,
  uid text,
  image text,
  text text,
  bg text default '#00a884',
  created_at timestamp default now(),
  expires_at timestamp
);

create table if not exists groups (
  id bigint generated by default as identity primary key,
  name text,
  image text,
  created_by text,
  created_at timestamp default now()
);

alter table groups add column if not exists image text;
alter table groups add column if not exists created_by text;

create table if not exists group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  uid text,
  role text default 'member'
);

alter table group_members add column if not exists role text default 'member';

create table if not exists group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade,
  sender_id text,
  text text,
  image text,
  audio text,
  type text default 'text',
  reply_to bigint,
  edited boolean default false,
  deleted_for_everyone boolean default false,
  created_at timestamp default now()
);

alter table group_messages add column if not exists image text;
alter table group_messages add column if not exists audio text;
alter table group_messages add column if not exists type text default 'text';
alter table group_messages add column if not exists reply_to bigint;
alter table group_messages add column if not exists edited boolean default false;
alter table group_messages add column if not exists deleted_for_everyone boolean default false;
alter table group_messages add column if not exists file_url text;
alter table group_messages add column if not exists file_name text;
alter table group_messages add column if not exists file_type text;

create table if not exists calls (
  id bigint generated by default as identity primary key,
  caller_id text,
  receiver_id text,
  type text,
  status text default 'ringing',
  offer jsonb,
  answer jsonb,
  ice jsonb default '[]'::jsonb,
  created_at timestamp default now()
);

create table if not exists blocked_users (
  id bigint generated by default as identity primary key,
  blocker_id text not null,
  blocked_id text not null,
  created_at timestamp default now(),
  unique(blocker_id, blocked_id)
);

create table if not exists muted_chats (
  id bigint generated by default as identity primary key,
  uid text not null,
  chat_type text not null,
  chat_id text not null,
  created_at timestamp default now(),
  unique(uid, chat_type, chat_id)
);

create table if not exists pinned_chats (
  id bigint generated by default as identity primary key,
  uid text not null,
  chat_type text not null,
  chat_id text not null,
  created_at timestamp default now(),
  unique(uid, chat_type, chat_id)
);

create table if not exists forwarded_messages (
  id bigint generated by default as identity primary key,
  from_message_id bigint,
  from_chat_type text,
  to_chat_type text,
  to_chat_id text,
  uid text,
  created_at timestamp default now()
);

alter table users enable row level security;
alter table private_chats enable row level security;
alter table deleted_messages enable row level security;
alter table message_reactions enable row level security;
alter table typing_status enable row level security;
alter table stories enable row level security;
alter table groups enable row level security;
alter table group_members enable row level security;
alter table group_messages enable row level security;
alter table calls enable row level security;
alter table blocked_users enable row level security;
alter table muted_chats enable row level security;
alter table pinned_chats enable row level security;
alter table forwarded_messages enable row level security;

do $$
begin
  create policy "users all" on users for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "private chats all" on private_chats for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "deleted messages all" on deleted_messages for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "reactions all" on message_reactions for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "typing all" on typing_status for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "stories all" on stories for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "groups all" on groups for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "group members all" on group_members for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "group messages all" on group_messages for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "calls all" on calls for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "blocked users all" on blocked_users for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "muted chats all" on muted_chats for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "pinned chats all" on pinned_chats for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "forwarded messages all" on forwarded_messages for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;

do $$
begin
  create policy "Allow uploads insert" on storage.objects for insert to authenticated with check (bucket_id = 'uploads');
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "Allow uploads select" on storage.objects for select to public using (bucket_id = 'uploads');
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "Allow uploads update" on storage.objects for update to authenticated using (bucket_id = 'uploads') with check (bucket_id = 'uploads');
exception when duplicate_object then null;
end $$;

do $$
begin
  create policy "Allow uploads delete" on storage.objects for delete to authenticated using (bucket_id = 'uploads');
exception when duplicate_object then null;
end $$;
